export const defauleMenus = [
  {
    "params": {},
    "menuId": 1,
    "menuName": "Monitor",
    "parentName": null,
    "parentId": 0,
    "path": "monitor",
    "component": null,
    "menuType": "M",
    "perms": "",
    "icon": "system",
    "children": []
  },
  {
    "params": {},
    "menuId": 2,
    "menuName": "Device",
    "parentName": null,
    "parentId": 0,
    "path": "device",
    "component": null,
    "menuType": "M",
    "perms": "",
    "icon": "monitor",
    "children": []
  },
  {
    "params": {},
    "menuId": 3,
    "menuName": "Configuration",
    "parentName": null,
    "parentId": 0,
    "path": "wireless",
    "component": null,
    "menuType": "M",
    "perms": "",
    "icon": "tool",
    "children": []
  },
  {
    "params": {},
    "menuId": 4,
    "menuName": "Organization",
    "parentName": null,
    "parentId": 0,
    "path": "company",
    "component": null,
    "menuType": "M",
    "perms": "",
    "icon": "tree",
    "children": []
  },
  {
    "params": {},
    "menuId": 5,
    "menuName": "Notification",
    "parentName": null,
    "parentId": 0,
    "path": "alarm",
    "component": null,
    "menuType": "M",
    "perms": "",
    "icon": "guide",
    "children": []
  },
  //monitor
  {
    "params": {},
    "menuId": 1101,
    "menuName": "Topology",
    "parentName": null,
    "parentId": 1,
    "path": "topo",
    "component": "monitor/topo/index",
    "menuType": "C",
    "perms": "monitor:topo:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1102,
    "menuName": "Site Distribution",
    "parentName": null,
    "parentId": 1,
    "path": "overview",
    "component": "monitor/overview/index",
    "menuType": "C",
    "perms": "monitor:overview:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1103,
    "menuName": "Logs",
    "parentName": null,
    "parentId": 1,
    "path": "log",
    "component": "ParentView",
    "menuType": "C",
    "perms": "monitor:logs:list",
    "icon": "",
    "children": []
  },
  //##logs
  {
    "params": {},
    "menuId": 11031,
    "menuName": "Operation Logs",
    "parentName": null,
    "parentId": 1103,
    "path": "operlog",
    "component": "monitor/logs/oper/index",
    "menuType": "C",
    "perms": "monitor:operlog:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 11032,
    "menuName": "Device Logs",
    "parentName": null,
    "parentId": 1103,
    "path": "devicelog",
    "component": "monitor/logs/device/index",
    "menuType": "C",
    "perms": "monitor:devicelog:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 11033,
    "menuName": "Terminal Logs",
    "parentName": null,
    "parentId": 1103,
    "path": "termlog",
    "component": "monitor/logs/terminal/index",
    "menuType": "C",
    "perms": "monitor:termlog:list",
    "icon": "",
    "children": []
  },
  //device
  {
    "params": {},
    "menuId": 1201,
    "menuName": "AC",
    "parentName": null,
    "parentId": 2,
    "path": "ac",
    "component": "device/ac/index",
    "menuType": "C",
    "perms": "device:ac:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1202,
    "menuName": "AP",
    "parentName": null,
    "parentId": 2,
    "path": "ap",
    "component": "device/ap/index",
    "menuType": "C",
    "perms": "device:ap:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1203,
    "menuName": "Gateway",
    "parentName": null,
    "parentId": 2,
    "path": "dcme",
    "component": "device/dcme/index",
    "menuType": "C",
    "perms": "device:dcme:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1204,
    "menuName": "Switch",
    "parentName": null,
    "parentId": 2,
    "path": "switch",
    "component": "device/switch/index",
    "menuType": "C",
    "perms": "device:switch:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1205,
    "menuName": "Controller",
    "parentName": null,
    "parentId": 2,
    "path": "controller",
    "component": "device/controller/index",
    "menuType": "C",
    "perms": "device:controller:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1206,
    "menuName": "Device Group",
    "parentName": null,
    "parentId": 2,
    "path": "deviceGroup",
    "component": "device/deviceGroup/index",
    "menuType": "C",
    "perms": "device:deviceGroup:list",
    "icon": "",
    "children": []
  },
  //wireless
  {
    "params": {},
    "menuId": 1301,
    "menuName": "Wireless",
    "parentName": null,
    "parentId": 3,
    "path": "netconfig",
    "component": "wireless/netconfig/index",
    "menuType": "C",
    "perms": "wireless:netconfig:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1302,
    "menuName": "Cloud Auth",
    "parentName": null,
    "parentId": 3,
    "path": "auth",
    "component": "wireless/auth/index",
    "menuType": "C",
    "perms": "wireless:auth:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1303,
    "menuName": "Strategy",
    "parentName": null,
    "parentId": 3,
    "path": "strategy",
    "component": "wireless/strategy/index",
    "menuType": "C",
    "perms": "wireless:strategy:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1304,
    "menuName": "Authentication",
    "parentName": null,
    "parentId": 3,
    "path": "msmconfig",
    "component": "wireless/msmconfig/index",
    "menuType": "C",
    "perms": "wireless:msmconfig:list",
    "icon": "",
    "children": []
  },
  //enterprise
  {
    "params": {},
    "menuId": 1401,
    "menuName": "Enterprise/Site",
    "parentName": null,
    "parentId": 4,
    "path": "list",
    "component": "company/list/index",
    "menuType": "C",
    "perms": "company:list:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1402,
    "menuName": "Administrator",
    "parentName": null,
    "parentId": 4,
    "path": "manager",
    "component": "company/manager/index",
    "menuType": "C",
    "perms": "company:manager:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1403,
    "menuName": "Cilent",
    "parentName": null,
    "parentId": 4,
    "path": "user",
    "component": "company/user/index",
    "menuType": "C",
    "perms": "company:user:list",
    "icon": "",
    "children": []
  },
  //alarm
  {
    "params": {},
    "menuId": 1501,
    "menuName": "Alarm",
    "parentName": null,
    "parentId": 5,
    "path": "alarmList",
    "component": "alarm/list/index",
    "menuType": "C",
    "perms": "alarm:list:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1502,
    "menuName": "Rules",
    "parentName": null,
    "parentId": 5,
    "path": "noticeSetting",
    "component": "alarm/noticeSetting/index",
    "menuType": "C",
    "perms": "alarm:noticeSetting:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1503,
    "menuName": "Settings",
    "parentName": null,
    "parentId": 5,
    "path": "alarmSetting",
    "component": "alarm/alarmSetting/index",
    "menuType": "C",
    "perms": "alarm:alarmSetting:list",
    "icon": "",
    "children": []
  },
  {
    "params": {},
    "menuId": 1504,
    "menuName": "Terminals",
    "parentName": null,
    "parentId": 5,
    "path": "monitoringUsers",
    "component": "alarm/monitoringUsers/index",
    "menuType": "C",
    "perms": "alarm:monitoringUsers:list",
    "icon": "",
    "children": []
  },
]